#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

#include "DIO_interface.h"


//PORTA
#define DIO_u8_PORTA_PIN_DIR_0    DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN_DIR_1    DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN_DIR_2    DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN_DIR_3    DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN_DIR_4    DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN_DIR_5    DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN_DIR_6    DIO_u8_OUTPUT
#define DIO_u8_PORTA_PIN_DIR_7    DIO_u8_OUTPUT


//PORTA
#define DIO_u8_PORTB_PIN_DIR_0    DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN_DIR_1    DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN_DIR_2    DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN_DIR_3    DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN_DIR_4    DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN_DIR_5    DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN_DIR_6    DIO_u8_OUTPUT
#define DIO_u8_PORTB_PIN_DIR_7    DIO_u8_OUTPUT

//PORTC
#define DIO_u8_PORTC_PIN_DIR_0    DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN_DIR_1    DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN_DIR_2    DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN_DIR_3    DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN_DIR_4    DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN_DIR_5    DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN_DIR_6    DIO_u8_OUTPUT
#define DIO_u8_PORTC_PIN_DIR_7    DIO_u8_OUTPUT

//PORTC
#define DIO_u8_PORTD_PIN_DIR_0    DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN_DIR_1    DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN_DIR_2    DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN_DIR_3    DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN_DIR_4    DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN_DIR_5    DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN_DIR_6    DIO_u8_OUTPUT
#define DIO_u8_PORTD_PIN_DIR_7    DIO_u8_OUTPUT

#endif
